import "./globals.css";
import ReduxProvider from "@/provider/ReduxProvider";


export const metadata = {
  title: "task-Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
        {children}
        </ReduxProvider>
        
      </body>
    </html>
  );
}
